"""initial schema

Revision ID: 45c2e0ad6e5c
Revises: 
Create Date: 2026-03-31 12:40:49.012237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45c2e0ad6e5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('campaign_id', sa.String(length=20), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('cpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaign_snapshots_customer_date', 'campaign_snapshots', ['customer_id', 'snapshot_date'], unique=False)
    op.create_table('change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('before_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('executed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_log_customer_executed', 'change_log', ['customer_id', 'executed_at'], unique=False)
    op.create_table('client_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('monthly_budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('generated_ad_copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('campaign_id', sa.String(length=20), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('headlines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_ad_copy')
    op.drop_table('client_accounts')
    op.drop_index('ix_change_log_customer_executed', table_name='change_log')
    op.drop_table('change_log')
    op.drop_index('ix_campaign_snapshots_customer_date', table_name='campaign_snapshots')
    op.drop_table('campaign_snapshots')
    # ### end Alembic commands ###
